ALTER TABLE oxorder DROP COLUMN TIRAMIZOO_TRACKING_URL;
ALTER TABLE oxorder DROP COLUMN TIRAMIZOO_STATUS;
ALTER TABLE oxorder DROP COLUMN TIRAMIZOO_PARAMS;

ALTER TABLE oxarticles DROP COLUMN OXTIRAMIZOOENABLE;
ALTER TABLE oxcategories DROP COLUMN OXTIRAMIZOOENABLE;

DELETE FROM oxdel2delset WHERE OXID = MD5(CONCAT('tiramizoo', 'tiramizoo'));
DELETE FROM oxdelivery WHERE OXID = 'tiramizoo';
DELETE FROM oxdeliveryset WHERE OXID = 'Tiramizoo';
DELETE FROM oxobject2payment WHERE OXOBJECTID = 'tiramizoo';

DELETE FROM oxconfig WHERE OXVARNAME LIKE 'oxTiramizoo%';