ALTER TABLE oxorder DROP COLUMN TIRAMIZOO_TRACKING_URL;
ALTER TABLE oxorder DROP COLUMN TIRAMIZOO_STATUS;
ALTER TABLE oxorder DROP COLUMN TIRAMIZOO_PARAMS;
ALTER TABLE oxorder DROP COLUMN TIRAMIZOO_EXTERNAL_ID;


ALTER TABLE oxarticles DROP COLUMN TIRAMIZOO_ENABLE;
ALTER TABLE oxcategories DROP COLUMN TIRAMIZOO_ENABLE;
ALTER TABLE oxcategories DROP COLUMN TIRAMIZOO_WIDTH;
ALTER TABLE oxcategories DROP COLUMN TIRAMIZOO_HEIGHT;
ALTER TABLE oxcategories DROP COLUMN TIRAMIZOO_LENGTH;
ALTER TABLE oxcategories DROP COLUMN TIRAMIZOO_WEIGHT;

DELETE FROM oxdel2delset WHERE OXID = MD5(CONCAT('tiramizoo', 'tiramizoo'));
DELETE FROM oxdelivery WHERE OXID = 'tiramizoo';
DELETE FROM oxdeliveryset WHERE OXID = 'Tiramizoo';
DELETE FROM oxobject2payment WHERE OXOBJECTID = 'tiramizoo';

DELETE FROM oxconfig WHERE OXVARNAME LIKE 'oxTiramizoo%';